export const teamMembersList = [
  {
    name: "Vicent Słomiński",
    avatar: "/src/assets/avatars/Vincent_Słomiński.jpg",
    role: "Team Lead Master Padawan",
    goals: [
      "Code Reviews",
      "User model and controllers with endpoints",
      "Pagination on transaction list",
      "Minor errors solving",
    ],
    difficulties: ["Making a reliable code review"],
    hobbies: ['Anime ( Especially "One Piece", "Naruto")', "Fantasy books"],
    linkedin: "https://www.linkedin.com/in/vincent-slominski/",
    github: "https://github.com/Okazaki92",
  },
  {
    name: "Dagmara Sobczak",
    avatar: "/src/assets/avatars/Dagmara_Sobczak.jpg",
    role: "Scrum Master Padawan",
    goals: [],
    difficulties: [],
    hobbies: [],
    linkedin: "https://www.linkedin.com/in/dagmara-sobczak-746076279/",
    github: "https://github.com/DagmaraSobczak",
  },
  {
    name: "Dorota Dudzik",
    avatar: "/src/assets/avatars/Dorota_Dudzik.jpg",
    role: "Developer Padawan",
    goals: [
      "Registration Page",
      "Balance Component",
      "Variables and global css styles",
      "Finance Store and Balance refreshing",
    ],
    difficulties: ["Put project time with private life together"],
    hobbies: ["Mountain walking", "Books reading", "Embroidery"],
    linkedin: "https://www.linkedin.com/in/dorota-dudzik-19b02a277/",
    github: "https://github.com/doradudzik",
  },
  {
    name: "Krystian Kowalik",
    avatar: "/src/assets/avatars/Krystian_Kowalik.jpg",
    role: "Developer Padawan",
    goals: [],
    difficulties: [],
    hobbies: [],
    linkedin: "https://www.linkedin.com/in/vincent-slominski/",
    github: "https://github.com/KRKDEV",
  },
  {
    name: "Karol Łaski",
    avatar: "/src/assets/avatars/Karol_Łaski.jpg",
    role: "Developer Padawan",
    goals: [
      "Register form component",
      "Chart component",
      "Table component",
      "Restricted Route",
      "Private Route",
      "Get Categories from server using Redux",
    ],
    difficulties: [
      "Put data from two endpoints request into one compact data that could be used in Table and Chart components",
    ],
    hobbies: ["Healthy lifestyle", "Functional Training", "Sport Activity"],
    linkedin: "https://www.linkedin.com/in/karol-%C5%82aski-b5663b293/",
    github: "https://github.com/karollaski",
  },
  {
    name: "Jacek Pasierb",
    avatar: "/src/assets/avatars/Jacek_Pasierb.jpg",
    role: "Developer Padawan",
    goals: [
      "Transaction model and controllers with endpoints",
      "Categories model and controllers with endpoints",
      "Statistic controllers with endpoints",
      "Errors handling",
      "Backend problems solving",
    ],
    difficulties: [
      "Put backend structure with response and endpoints to match frontend requests",
    ],
    hobbies: ["Fishing"],
    linkedin: "https://www.linkedin.com/in/jacek-pasierb/",
    github: "https://www.linkedin.com/in/jacek-pasierb",
  },
  {
    name: "Hanna Rogalska",
    avatar: "/src/assets/avatars/Hanna_Rogalska.jpg",
    role: "Developer Padawan",
    goals: [],
    difficulties: [],
    hobbies: [],
    linkedin: "https://www.linkedin.com/in/hanna-rogalska-246362276/",
    github: "https://github.com/HannaRogalska",
  },
  {
    name: "Edyta Sowa",
    avatar: "/src/assets/avatars/Edyta_Sowa.jpg",
    role: "Developer Padawan",
    goals: [],
    difficulties: [],
    hobbies: [],
    linkedin: "https://www.linkedin.com/in/edyta-sowa/",
    github: "https://github.com/EdytaSowa",
  },
];
